/// Flutter icons FiveRingsDB
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  FiveRingsDB
///      fonts:
///       - asset: fonts/FiveRingsDB.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class FiveRingsDB {
  FiveRingsDB._();

  static const _kFontFam = 'FiveRingsDB';

  static const IconData conflict_military = const IconData(0xe900, fontFamily: _kFontFam);
  static const IconData conflict_political = const IconData(0xe901, fontFamily: _kFontFam);
  static const IconData element_air = const IconData(0xe902, fontFamily: _kFontFam);
  static const IconData element_earth = const IconData(0xe903, fontFamily: _kFontFam);
  static const IconData element_fire = const IconData(0xe904, fontFamily: _kFontFam);
  static const IconData element_void = const IconData(0xe905, fontFamily: _kFontFam);
  static const IconData element_water = const IconData(0xe906, fontFamily: _kFontFam);
  static const IconData clan_crab = const IconData(0xe907, fontFamily: _kFontFam);
  static const IconData clan_crane = const IconData(0xe908, fontFamily: _kFontFam);
  static const IconData clan_dragon = const IconData(0xe909, fontFamily: _kFontFam);
  static const IconData clan_lion = const IconData(0xe90a, fontFamily: _kFontFam);
  static const IconData clan_phoenix = const IconData(0xe90b, fontFamily: _kFontFam);
  static const IconData clan_scorpion = const IconData(0xe90c, fontFamily: _kFontFam);
  static const IconData clan_unicorn = const IconData(0xe90d, fontFamily: _kFontFam);
  static const IconData unique = const IconData(0xe90e, fontFamily: _kFontFam);
  static const IconData clan_neutral = const IconData(0xe90f, fontFamily: _kFontFam);
  static const IconData element_all = const IconData(0xe910, fontFamily: _kFontFam);
}
